<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sistema de Banco - {{title}}</title>
    {% for css in assets.css %}
        <link rel="stylesheet" href="./Public/Assets/css/{{css}}">
    {% endfor %}
</head>
<body>
